### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by sapioit** [bisrael/even.less#1]
Hi,

I only have one question:
Shouldn't nln() be iln()?

.nln() --> inline
.iln() --> inline
.iblk() --> inline-block
.blk() --> block

It doesen't adds up...

Have a good day!

**Comment by bisrael** [comment]
Good point.

Probably should support both, as well as `.nblk() --> inline-block`

I'm happy to accept Pull Requests :)

**Comment by bisrael** [comment]
Pull Request Merged
